### PR TITLE
FR: add placeholder at text filter widget

### PR DESCRIPTION
**Pull request by zonky2**
FR: add placeholder at text filter widget

BE:
shot160

FE:
shot161

siehe https://github.com/MetaModels/core/issues/916

### CODE REVIEW

**Comment by stefanheimes** [comment]
Should we add this as a core feature from MetaModels ? @discordier

**Comment by discordier** [comment]
@stefanheimes we once hat this at the core. (see [PR 919](https://github.com/MetaModels/core/pull/919))
I declined it in https://github.com/MetaModels/core/pull/919#issuecomment-191331829 because as far as I know the only filter supporting placeholders is the text field.
Therefore it does not make sense to add it to the core as nothing else will ever use it.

**Comment by zonky2** [comment]
the PR sleeps since five months :-(

**Comment by cliffparnitzky** [comment]
Tested in my environment. Works fine.

I think the milestone is wrong ... must be 2.0.0

**Comment by discordier** [comment]
Thanks @cliffparnitzky, fixed.

**Comment by zonky2** [comment]
implemented with alpha-5

**Pull request closed without merging**
