### PR TITLE
Htaccess

### PR DESCRIPTION
**Pull request by xantippe**

### CODE REVIEW

**Comment by discordier** [comment]
Can not merge as this contains the changes from #19 as well. :(
You MUST create separate branches for unrelated changes when filing PRs.

**Comment by xantippe** [comment]
ja... :-( sollte eigentlich separat kommen...

**Comment by discordier** [comment]
Could you cherry pick the commit into a separate PR please?

**Comment by xantippe** [comment]
pls delete this

**Comment by discordier** [comment]
Simply close it yourself next time.

**Pull request closed without merging**
